### ISSUE TITLE
請問怎樣和NavigationLink共同存在？

### ISSUE THREAD

**Issue by carlhung** [fatbobman/SwipeCell#1]
我的問題像你的例字：
    ScrollView{
        LazyVStack{
        ForEach(lists,id:\.self){ item in
           Text("Swipe in scrollView:\(item)")
            .frame(height:80)
            .swipeCell(cellPosition: .both, leftSlot:slot, rightSlot: slot)
            .dismissSwipeCellForScrollViewForLazyVStack()
        }
        }
    }

我試加入NavigationLink在Text外層，不成功。
移除了swipeCell就可以用NavigationLink

**Comment by fatbobman** [comment]
你好.我试了一下,应该是好用的

import SwiftUI
import SwipeCell

struct Test: View {
    var body: some View {
        let button1 = SwipeCellButton(buttonStyle: .titleAndImage, title: "Mark", systemImage: "bookmark", titleColor: .white, imageColor: .white, view: nil, backgroundColor: .green, action: {}, feedback:true)
        let button2 = SwipeCellButton(buttonStyle: .titleAndImage, title: "New", systemImage: "plus.square", view:nil, backgroundColor: .blue, action: {})
        let slot = SwipeCellSlot(slots: [button2,button1])
        return
            NavigationView{
                ScrollView{
                    LazyVStack{
                        ForEach(0..<100){ item in
                            NavigationLink("test",destination:Text("Swipe in scrollView:\(item)"))
                                .frame(height:80)
                                .swipeCell(cellPosition: .both, leftSlot:slot, rightSlot: slot)
                                .dismissSwipeCellForScrollViewForLazyVStack()
                            
                        }
                    }
                }
        }
    }
}

> 2020年10月9日 下午5:19，carlhung <notifications@github.com> 写道：
> 
> ScrollView{
> LazyVStack{
> ForEach(lists,id:.self){ item in
> Text("Swipe in scrollView:(item)")
> .frame(height:80)
> .swipeCell(cellPosition: .both, leftSlot:slot, rightSlot: slot)
> .dismissSwipeCellForScrollViewForLazyVStack()
> }
> }
> }

**Comment by fatbobman** [comment]
如果你想让整个link都变成可点击的话,需要做一点处理

import SwiftUI
import SwipeCell

struct Test: View {
    var body: some View {
        let button1 = SwipeCellButton(buttonStyle: .titleAndImage, title: "Mark", systemImage: "bookmark", titleColor: .white, imageColor: .white, view: nil, backgroundColor: .green, action: {}, feedback:true)
        let button2 = SwipeCellButton(buttonStyle: .titleAndImage, title: "New", systemImage: "plus.square", view:nil, backgroundColor: .blue, action: {})
        let slot = SwipeCellSlot(slots: [button2,button1])
        return
            NavigationView{
                ScrollView{
                    LazyVStack{
                        ForEach(0..<100){ item in
                            NavigationLink(destination:Text("Swipe in scrollView:\(item)"),label:linkButton)
                                .frame(height:80)
                                .swipeCell(cellPosition: .both, leftSlot:slot, rightSlot: slot)
                                .dismissSwipeCellForScrollViewForLazyVStack()
                        }
                    }
                }
        }
    }
    
    func linkButton() -> some View{
        HStack{
            Text("test")
            Spacer()
        }
        .contentShape(Rectangle())
    }
}

**Comment by carlhung** [comment]
因為我的Text是從一個@State array中的element得來，而且有一個button可加入新element到array中，如果我用ForEach(_: Range<Int>)寫入會得到error. 說ForEach(_: Range<Int>)只能用在constant.

**Comment by fatbobman** [comment]
通常这种情况ForEach(items, id:\.self)就能解决.
不过我没有看到你的代码,没法更好的说明
