### ISSUE TITLE
Can we define Accesibility mode/VoiceOver empty "Alt" contents for Icon Images/Labels ?

### ISSUE THREAD

**Issue by friguron** [fatbobman/SwipeCell#15]
Is there any current mechanism to define the "Alt" readable text for the slot action icon (typical trashcan), or even the "Alt" action text description label (typical "Erase") when creating the SwipeCellButton ?

Imagine I'd like to create a swipeable Slot with a typical "Trashcan icon" +  "Erase"  text, but I don't want to allow VoiceOver to read those contents (So I'd fill the "Alt" version of those elements with just empty strings).

I've started to implement some ideas on my own, but all of them need messing with the actual code of the library, and I'd like to define those "Alt" contents from the "outside" of the library, AKA when creating the SwipeCellButton, and then passing them to the library in the constructor of said button...

Is it possible as of now?

Greetings...

**Comment by fatbobman** [comment]
I haven't tested it and don't know if it works to add it there

```swift
let button3 = SwipeCellButton(buttonStyle: .view, title:"",systemImage: "", view: {
    AnyView(
        Group{
            if unread {
                Image(systemName: "envelope.badge")
                    .foregroundColor(.white)
                    .font(.title)
            }
            else {
                Image(systemName: "envelope.open")
                    .foregroundColor(.white)
                    .font(.title)
            }
        }.accessibilityLabel("some words")   //  add to here
    )
}, backgroundColor: .orange, action: {unread.toggle()}, feedback: false)
```

**Comment by friguron** [comment]
Seems a witty idea, I'll try and report, thanks!!
