### ISSUE TITLE
Issue to activate it. only works when I have both fingers pressing and try a drag

### ISSUE THREAD

**Issue by hopye** [fatbobman/SwipeCell#19]
I have a weird behavior, im using iOS 17.

have tested in the view, but it only reveal the swipe button when I do a pinch gesture or kinda hold the finger in one element and then do a drag on the other and then in both I get the swipe button reveal...

**Comment by fatbobman** [comment]
Can you provide a minimally implemented code to facilitate troubleshooting?
BTW: The first few iOS 17 versions usually have some weird behavior.

**Comment by hopye** [comment]
im closing, after debbuging and debugging, i had a  Drag gesture on a motherView() the gesture from the .swipecell and my gesture were conflicting. what i did is make the gesture attached/active only when the sidebar is opened...
