### ISSUE TITLE
swiftui-introspect 版本依赖冲突

### ISSUE THREAD

**Issue by ajunjunandtmac** [fatbobman/SwipeCell#20]
大神你好，我是看着你的博客一点一点学SwiftUI的，非常感谢！！！
现在遇到一个问题，我用SPM引入了最新的[SwiftUI-Introspect](https://github.com/siteline/swiftui-introspect.git) 1.1.1版本
现在再想引入您这个库，但是这个库的依赖是0.1.4版本，现在好像引入不了
我是SPM新手，需要我把introspect的指定版本号降级下来吗？
![9E9CA02D-D733-457F-A56B-58D2F0DC7276](https://github.com/fatbobman/SwipeCell/assets/14208608/0c5df415-9fe5-4734-94f1-a124f37d557d)

**Comment by fatbobman** [comment]
> 大神你好，我是看着你的博客一点一点学SwiftUI的，非常感谢！！！ 现在遇到一个问题，我用SPM引入了最新的[SwiftUI-Introspect](https://github.com/siteline/swiftui-introspect.git) 1.1.1版本 现在再想引入您这个库，但是这个库的依赖是0.1.4版本，现在好像引入不了 我是SPM新手，需要我把introspect的指定版本号降级下来吗？ ![9E9CA02D-D733-457F-A56B-58D2F0DC7276](https://user-images.githubusercontent.com/14208608/278800719-0c5df415-9fe5-4734-94f1-a124f37d557d.png)

你好，Introspect 在 1.0 后有了很大的变化。这个库我也很久没有更新了。
我创建了一个新的 Branch ：Introspect_12.0 
 https://github.com/fatbobman/SwipeCell/tree/Introspect_12.0
 你引入这个 branch 就 ok 了。
在这里面我将 0.12.0 版本的 Introspect 代码集成进去了。并且去掉了它代码中的 public ，避免冲突。
不过，由于从 iOS 16 开始，SwiftUI List 的底层实现又了变化，因此，目前的代码在 iOS 16、17 中，对 List 下的滑动菜单支持有点问题。滑出滚动后无法回位。
我暂时没有时间去调整这个问题。如果使用的话，可以考虑使用 LazyVStack

**Comment by ajunjunandtmac** [comment]
> > 大神你好，我是看着你的博客一点一点学SwiftUI的，非常感谢！！！ 现在遇到一个问题，我用SPM引入了最新的[SwiftUI-Introspect](https://github.com/siteline/swiftui-introspect.git) 1.1.1版本 现在再想引入您这个库，但是这个库的依赖是0.1.4版本，现在好像引入不了 我是SPM新手，需要我把introspect的指定版本号降级下来吗？ ![9E9CA02D-D733-457F-A56B-58D2F0DC7276](https://user-images.githubusercontent.com/14208608/278800719-0c5df415-9fe5-4734-94f1-a124f37d557d.png)
> 
> 你好，Introspect 在 1.0 后有了很大的变化。这个库我也很久没有更新了。 我创建了一个新的 Branch ：Introspect_12.0 https://github.com/fatbobman/SwipeCell/tree/Introspect_12.0 你引入这个 branch 就 ok 了。 在这里面我将 0.12.0 版本的 Introspect 代码集成进去了。并且去掉了它代码中的 public ，避免冲突。 不过，由于从 iOS 16 开始，SwiftUI List 的底层实现又了变化，因此，目前的代码在 iOS 16、17 中，对 List 下的滑动菜单支持有点问题。滑出滚动后无法回位。 我暂时没有时间去调整这个问题。如果使用的话，可以考虑使用 LazyVStack

正好，我就没打算用List。因为列表要支持上拉刷新下拉加载，这个我目前找到的方案只能是自定义ScrollView，再配合您这个库用LazyVStack+Foreach去实现左滑菜单。 在UIKit时代很容易实现的需求现在在SwiftUI里实现起来很艰难。
