### ISSUE TITLE
Xcode16.1 / iOS18.2 Scrollview不能滚动

### ISSUE THREAD

**Issue by gujia2312** [fatbobman/SwipeCell#26]
在Xcode16.1 / iOS18.2上跑了Demo，能响应cell的左滑右滑事件、按钮点击事件，但是页面不能滚动！

**Comment by ajunjunandtmac** [comment]
我也遇到了相同的问题 @fatbobman 堂主是否有空看一下，多谢多谢！

**Comment by fatbobman** [comment]
调整了一下，应该是修复了。在 SwiftUI 提供了 SwipeAction 后，我基本上没有再维护这个库了。或许有时间会重写一个吧

**Comment by gujia2312** [comment]
@fatbobman 不好意思，麻烦你再帮忙看下这个问题：
虽然在Xcode16 iOS18上修复了这个问题，但是Xcode16 iOS17上scrollView不能滚动了，且无法响应cell点击事件。

**Comment by fatbobman** [comment]
@gujia2312 已更新，做了兼容性的处理

**Comment by gujia2312** [comment]
@fatbobman 很抱歉再次打扰到你！
我现在用的分支是：Introspect_12.0，能帮忙把你最新的改动更新到这个分支上吗？

**Comment by fatbobman** [comment]
@gujia2312 已更新，没打 tag，直接使用 Introspect_12.0 的最新代码即可

**Comment by gujia2312** [comment]
可以了，谢谢博主！
