### ISSUE TITLE
ForEach 里加了 SwipeCell 每个 View 下面都会空一小截，想问下是怎么产生的，能不能去掉

### ISSUE THREAD

**Issue by firerainky** [fatbobman/SwipeCell#3]
```
var body: some View {
        
        let editButton = SwipeCellButton(
            buttonStyle: .title,
            title: "Edit",
            systemImage: nil,
            view: nil,
            backgroundColor: .green) {
                print("Edit")
            }
        let deleteButton = SwipeCellButton(
            buttonStyle: .title,
            title: "Delete",
            systemImage: nil,
            view: nil,
            backgroundColor: .red) {
                print("Delete")
            }
        return ScrollView { ForEach(0..<4) {_ in
            HStack {
                Text("Hello")
                Spacer()
            }.frame(height: 150).background(Color.blue)
                .swipeCell(cellPosition: .right, leftSlot: nil, rightSlot: SwipeCellSlot(slots: [editButton, deleteButton]))
}
```
<img width="361" alt="Screen Shot 2020-11-13 at 5 02 44 PM" src="https://user-images.githubusercontent.com/8377163/99049904-5f782000-25d2-11eb-984d-f88ab6acda59.png">

就是中间白色那几条，注释掉SwipeCell就没了

**Comment by firerainky** [comment]
跑了下demo，和readme 里的图片不太一样，readme 里图片每个cell 都是占满的而且有分隔线，readme 里图片是用的 list?

**Comment by fatbobman** [comment]
```swift
        return ScrollView {
            LazyVStack(spacing:0){
            ForEach(0..<4) { _ in
                HStack {
                    Text("Hello")
                    Spacer()
                }.frame(height: 150).background(Color.blue)
                .swipeCell(
                        cellPosition: .right,
                        leftSlot: nil,
                        rightSlot: SwipeCellSlot(slots: [editButton, deleteButton])
                    )
                }
            }
        }
```

加入LazyVStask或者VStack控制一下spacing 就行

**Comment by firerainky** [comment]
又忘了这个 spacing = =b
但是为什么不加 swipecell 就没有这小块空档了呢～

**Comment by zhouzhuhao** [comment]
> ```
> var body: some View {
>         
>         let editButton = SwipeCellButton(
>             buttonStyle: .title,
>             title: "Edit",
>             systemImage: nil,
>             view: nil,
>             backgroundColor: .green) {
>                 print("Edit")
>             }
>         let deleteButton = SwipeCellButton(
>             buttonStyle: .title,
>             title: "Delete",
>             systemImage: nil,
>             view: nil,
>             backgroundColor: .red) {
>                 print("Delete")
>             }
>         return ScrollView { ForEach(0..<4) {_ in
>             HStack {
>                 Text("Hello")
>                 Spacer()
>             }.frame(height: 150).background(Color.blue)
>                 .swipeCell(cellPosition: .right, leftSlot: nil, rightSlot: SwipeCellSlot(slots: [editButton, deleteButton]))
> }
> ```
> 
> <img alt="Screen Shot 2020-11-13 at 5 02 44 PM" width="361" src="https://user-images.githubusercontent.com/8377163/99049904-5f782000-25d2-11eb-984d-f88ab6acda59.png">
> 
> 就是中间白色那几条，注释掉SwipeCell就没

**Comment by zhouzhuhao** [comment]
怎么知道删除的那个item的index,然后更新数据源啊？
