### ISSUE TITLE
大佬，我怎么才能在action中是知道删除哪个item啊？ 

### ISSUE THREAD

**Issue by zhouzhuhao** [fatbobman/SwipeCell#6]
如题

**Comment by fatbobman** [comment]
在ForEach中定义button。其他类似数组、CorData可以使用id来确定需要删除的item
```swift
struct ContentView: View {
    var body: some View {
        ForEach(0..<100){ i in
            let button1 = SwipeCellButton(
                buttonStyle: .titleAndImage,
                title: "Delete",
                systemImage: "trash",
                titleColor: .white,
                imageColor: .white,
                view: nil,
                backgroundColor: .green,
                action: {
                    print("should delete \(i)")
                },
                feedback: true
            )

            let slot1 = SwipeCellSlot(slots: [button1])

            Text("id:\(i)")
                .frame(height:100)
                .swipeCell(cellPosition: .left, leftSlot: slot1, rightSlot: nil)
        }
    }
}
```

**Comment by zhouzhuhao** [comment]
> 在ForEach中定义button。其他类似数组、CorData可以使用id来确定需要删除的item
> 
> ```swift
> struct ContentView: View {
>     var body: some View {
>         ForEach(0..<100){ i in
>             let button1 = SwipeCellButton(
>                 buttonStyle: .titleAndImage,
>                 title: "Delete",
>                 systemImage: "trash",
>                 titleColor: .white,
>                 imageColor: .white,
>                 view: nil,
>                 backgroundColor: .green,
>                 action: {
>                     print("should delete \(i)")
>                 },
>                 feedback: true
>             )
> 
>             let slot1 = SwipeCellSlot(slots: [button1])
> 
>             Text("id:\(i)")
>                 .frame(height:100)
>                 .swipeCell(cellPosition: .left, leftSlot: slot1, rightSlot: nil)
>         }
>     }
> }
> ```

谢谢大佬，我去试一下

**Comment by zhouzhuhao** [comment]
iOS13不支持？？

**Comment by fatbobman** [comment]
是的。使用了SwiftUI2.0的部分特性。需要iOS14
ReadMe里有说明
