### ISSUE TITLE
Navigation  Link swipe does not work

### ISSUE THREAD

**Issue by Patresko** [fatbobman/SwipeCell#9]
ScrollView(.vertical, showsIndicators: false) {
                LazyVStack(alignment: .leading) {`
NavigationLink(destination:
                                        LiftDetail(lift: lift, categoryID: category.id)
                                            .environmentObject(localization)
                                    ){
                                        Lift(
                                            title: getText(liftObj: lift, language: localization.primaryLanguage).code,
                                            description: getText(liftObj: lift, language: localization.primaryLanguage).title,
                                            img: getText(liftObj: lift, language: localization.primaryLanguage).photoId
                                        )
                                        .id(UUID())
                                    }
                                    .frame(height:80)
                                    .swipeCell(cellPosition: .both, leftSlot:slot1, rightSlot: slot1)
                                    .dismissSwipeCellForScrollViewForLazyVStack()
}
}`

I have code like this but swiping does not trigger at all

**Comment by bcyng** [comment]
this doesn't allow the user to tap on the cell to navigate. it required the user to swipe and then click on one of the buttons.

**Comment by skywalkerlw** [comment]
onTapGesture may be a better way

**Comment by actlikeacrazy** [comment]
Can someone elaborate on the onTapGesture ? 
I have a custom View that I use as cells in ScrollView, now that cell has swipeCell modifier. When I wrap the cell in navigationLink, it shows that tap gesture when cell is tapped but nothings happening. If I remove the swipe cell modifier im in the game. But I guess the drag gesture recogniser in swipe cell api is invalidated notification about onTap ?

**Comment by fatbobman** [comment]
```swift
crollView {
            LazyVStack {
                ForEach(lists, id: \.self) { item in
                    Text("Swipe in scrollView:\(item)") // cell
                        .onTapGesture {   // add onTap at cell to trigger navigationLink
                            i = item
                            DispatchQueue.main.asyncAfter(deadline: .now() + 0.1){
                                go.toggle()
                            }
                        }
                        .frame(height: 80)
                        .swipeCell(cellPosition: .both, leftSlot: slot, rightSlot: slot)
                        .dismissSwipeCellForScrollViewForLazyVStack()
                }
            }
        }
        .background(
            NavigationLink("", destination: Text("\(i)"), isActive: $go)
                .frame(width:0,height:0)
        )
```

**Comment by twodayslate** [comment]
For newer code you'll have to push to the navigation stack since NavigationLink with isActive is deprecated.
